apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  count: 3
  version: 8.6.1
  config:
    log.level: info
    api.http.host: "0.0.0.0"
    queue.type: memory
    config.reload.automatic: true
  pipelines:
    - pipeline.id: main
      config.string: input { http { } } output { stdout { } }
  services:
    - name: http
      service:
        spec:
          type: ClusterIP
          ports:
            - port: 8080
              name: "httpinput"
              protocol: TCP
              targetPort: 8080
  podTemplate:
    spec:
      containers:
        - name: logstash
